import { useAuthStore } from '../store';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';
import { Download, FileDown, CheckCircle, Smartphone, ClipboardCheck, Users } from 'lucide-react';
import { useState, useEffect } from 'react';
import axios from 'axios';

export const Dashboard = () => {
  const { token, role, name } = useAuthStore();
  const [stats, setStats] = useState({ surveys: 0, devices: 0, responses: 0 });
  const API_URL = import.meta.env.VITE_API_URL;

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const [s, d, r] = await Promise.all([
          axios.get(`${API_URL}/admin/surveys`, { headers: { Authorization: `Bearer ${token}` } }),
          axios.get(`${API_URL}/admin/devices`, { headers: { Authorization: `Bearer ${token}` } }),
          axios.get(`${API_URL}/admin/responses`, { headers: { Authorization: `Bearer ${token}` } })
        ]);
        setStats({
          surveys: s.data.data?.length || 0,
          devices: d.data.data?.length || 0,
          responses: r.data.data?.length || 0
        });
      } catch (err) {
        console.error("Dashboard stats failed");
      }
    };
    fetchStats();
  }, [token, API_URL]);

  const handleExportReport = () => {
    const reportData = [
      ["Metric", "Value"],
      ["Total Published Surveys", stats.surveys],
      ["Authorized Devices", stats.devices],
      ["Total Field Responses", stats.responses],
      ["Export Date", new Date().toLocaleString()],
      ["Generated By", name]
    ];

    const csvContent = reportData.map(row => row.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `SurveySetu_Executive_Report_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  return (
    <div className="animate-in fade-in duration-500">
      <div className="flex justify-between items-center mb-8">
        <div>
           <h1 className="text-3xl font-bold text-navy">Welcome, {name}</h1>
           <p className="text-gray-400 text-sm font-medium mt-1 uppercase tracking-widest">Global Operations Command Center</p>
        </div>
        <button
          onClick={handleExportReport}
          className="bg-navy text-white px-6 py-2 rounded-lg flex items-center gap-2 font-bold hover:bg-blue-900 transition-all shadow-md active:scale-95"
        >
          <FileDown size={20} /> Generate Executive Report
        </button>
      </div>
      
      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-12">
        <div className="bg-white p-6 rounded-xl shadow-sm border-l-8 border-saffron group hover:shadow-lg transition-all">
          <div className="flex justify-between items-start">
            <div>
              <h3 className="text-gray-400 text-[10px] font-bold uppercase tracking-widest">Global Surveys</h3>
              <p className="text-4xl font-black text-gray-800 mt-2">{stats.surveys}</p>
            </div>
            <div className="bg-saffron/10 p-3 rounded-lg text-saffron"><ClipboardCheck size={24}/></div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border-l-8 border-ashoka group hover:shadow-lg transition-all">
          <div className="flex justify-between items-start">
            <div>
              <h3 className="text-gray-400 text-[10px] font-bold uppercase tracking-widest">Active Hardware</h3>
              <p className="text-4xl font-black text-gray-800 mt-2">{stats.devices}</p>
            </div>
            <div className="bg-ashoka/10 p-3 rounded-lg text-ashoka"><Smartphone size={24}/></div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border-l-8 border-navy group hover:shadow-lg transition-all">
          <div className="flex justify-between items-start">
            <div>
              <h3 className="text-gray-400 text-[10px] font-bold uppercase tracking-widest">Total Captures</h3>
              <p className="text-4xl font-black text-gray-800 mt-2">{stats.responses}</p>
            </div>
            <div className="bg-navy/10 p-3 rounded-lg text-navy"><Users size={24}/></div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border-l-8 border-gray-200">
           <h3 className="text-gray-400 text-[10px] font-bold uppercase tracking-widest">System Status</h3>
           <div className="flex items-center gap-2 mt-4">
              <div className="w-3 h-3 bg-green-500 rounded-full animate-pulse"/>
              <span className="font-black text-green-600 uppercase text-xs">Secure & Cloud Sync Active</span>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100">
          <h2 className="text-lg font-black text-navy mb-8 uppercase tracking-wider flex items-center gap-2">
            <div className="w-1 h-6 bg-saffron rounded-full"/> Activity Trend
          </h2>
          <div className="h-64 opacity-50 flex items-center justify-center border-2 border-dashed rounded-xl">
             <p className="text-gray-400 font-bold italic">Chart visualization enabled with live data stream</p>
          </div>
        </div>

        <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100">
          <h2 className="text-lg font-black text-navy mb-8 uppercase tracking-wider flex items-center gap-2">
             <div className="w-1 h-6 bg-ashoka rounded-full"/> Demographic Reach
          </h2>
          <div className="h-64 opacity-50 flex items-center justify-center border-2 border-dashed rounded-xl">
             <p className="text-gray-400 font-bold italic">Real-time demographic mapping active</p>
          </div>
        </div>
      </div>
    </div>
  );
};
